[package]
name = "solana_copy_trade_bot_wsl"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
solana-sdk = "1.18.26"
solana-client = "1.18.26"
anyhow = "1.0.80"
serde_json = "1.0"
futures-util = "0.3"
solana-transaction-status = "1.18.26"